import { Game } from "../../types";

export const games: Game[] = [
  {
    name: "The Legend of Zelda",
    year: 1986,
    console: "nes",
    src: "https://upload.wikimedia.org/wikipedia/en/4/41/Legend_of_zelda_cover_%28with_cartridge%29_gold.png",
  },
  {
    name: "Zelda II: The Adventure Of Link",
    year: 1987,
    console: "nes",
    src: "https://upload.wikimedia.org/wikipedia/en/f/fd/Zelda_II_The_Adventure_of_Link_box.jpg",
  },
  {
    name: "Zelda Game & Watch",
    year: 1989,
    console: "g&w",
    src: "https://www.zeldadungeon.net/wiki/images/b/b5/Zelda_G%26W_Boxart.jpg",
  },
  {
    name: "The Legend of Zelda - Nelsonic Game Watch",
    year: 1989,
    console: "g&w",
    src: "https://lh3.googleusercontent.com/ci/AEwo86fBFyH5O_o3Tmq32WHhm062FxDBCXm_EB2p6pBHmITxEQWZymLYHADm8bSGqevkhIkSZlKl6xc=s1200",
  },
  {
    name: "The Legend of Zelda: A Link to the Past",
    year: 1991,
    console: "supernes",
    src: "https://upload.wikimedia.org/wikipedia/en/2/21/The_Legend_of_Zelda_A_Link_to_the_Past_SNES_Game_Cover.jpg",
  },
  {
    name: "The Legend of Zelda: Link's Awakening",
    year: 1993,
    console: "gb",
    src: "https://upload.wikimedia.org/wikipedia/en/c/c1/Link%27s_Awakening.png",
  },
  {
    name: "Zelda no Densetsu 1 - The Hyrule Fantasy",
    year: 1994,
    console: "nes",
    src: "https://s.pacn.ws/1/p/PA.54166.001.jpg",
  },
  {
    name: "BS The Legend of Zelda: Ancient Stone Tablets",
    year: 1997,
    console: "supernes",
    src: "https://www.romhacking.net/translations/snes/images/1460titlescreen.png",
  },
  {
    name: "Zelda no Densetsu: Kamigami no Triforce",
    year: 1997,
    console: "supernes",
    src: "http://www.videogameden.com/sfc/cover/zel.jpg",
  },
  {
    name: "The Legend of Zelda: Ocarina of Time",
    year: 1998,
    console: "n64",
    src: "https://upload.wikimedia.org/wikipedia/en/5/57/The_Legend_of_Zelda_Ocarina_of_Time.jpg",
  },
  {
    name: "The Legend of Zelda: Link's Awakening DX",
    year: 1998,
    console: "gbcolor",
    src: "https://static.wikia.nocookie.net/zelda_gamepedia_en/images/9/9a/LADX_NA_Box_Art.png",
  },
  {
    name: "The Legend of Zelda: Majora's Mask",
    year: 2000,
    console: "n64",
    src: "https://upload.wikimedia.org/wikipedia/en/6/60/The_Legend_of_Zelda_-_Majora%27s_Mask_Box_Art.jpg",
  },
  {
    name: "The Legend of Zelda: Oracle of Ages",
    year: 2001,
    console: "gbcolor",
    src: "https://cache.romsgames.net/static/44817f9c658ad7f176983d05fae971b200256cae/image.jpeg",
  },
  {
    name: "The Legend of Zelda: Oracle of Seasons",
    year: 2001,
    console: "gbcolor",
    src: "https://techtoroms.com/wp-content/uploads/2023/02/The-Legend-of-Zelda-Oracle-of-Seasons-ROM-GBC.jpeg",
  },
  {
    name: "The Legend of Zelda: The Wind Waker",
    year: 2002,
    console: "gamecube",
    src: "https://upload.wikimedia.org/wikipedia/en/7/79/The_Legend_of_Zelda_The_Wind_Waker.jpg",
  },
  {
    name: "The Legend of Zelda: Ocarina of Time Master Quest",
    year: 2002,
    console: "gamecube",
    src: "https://static.wikia.nocookie.net/zelda_gamepedia_en/images/6/61/Mqusbox.jpg",
  },
  {
    name: "The Legend of Zelda: Collector's Edition",
    year: 2003,
    console: "gamecube",
    src: "https://static.wikia.nocookie.net/zelda_gamepedia_en/images/4/46/CollectorsEdition.jpg",
  },
  {
    name: "The Legend of Zelda: The Minish Cap",
    year: 2004,
    console: "gbadvance",
    src: "https://static.wikia.nocookie.net/zelda_gamepedia_en/images/9/93/ZeldaMinishCap_BoxArt.jpg",
  },
  {
    name: "The Legend of Zelda: Twilight Princess",
    year: 2006,
    console: "gamecube",
    src: "https://www.lukiegames.com/assets/images/GC/gc_zelda_twilight_princess_p_7cxg6h.jpg",
  },
  {
    name: "Freshly-Picked Tingle's Rosy Rupeeland",
    year: 2006,
    console: "nds",
    src: "https://static.wikia.nocookie.net/zelda_gamepedia_en/images/8/81/FPTRR_UK_Box_Art.jpg",
  },
  {
    name: "The Legend of Zelda: Phantom Hourglass",
    year: 2007,
    console: "nds",
    src: "https://m.media-amazon.com/images/M/MV5BMTY4OTQ2NTA4M15BMl5BanBnXkFtZTgwNjE5MTk4MDE@._V1_.jpg",
  },
  {
    name: "Tingle's Balloon Fight DS",
    year: 2007,
    console: "nds",
    src: "https://static.wikia.nocookie.net/zelda/images/f/fb/Tingle%27s_Balloon_Fight_DS_cover.jpg",
  },
  {
    name: "Link's Crossbow Training",
    year: 2007,
    console: "wii",
    src: "https://static.wikia.nocookie.net/zelda/images/9/9a/Link%27s_Crossbow_Training_%28European%29.png",
  },
  {
    name: "The Legend of Zelda: Spirit Tracks",
    year: 2009,
    console: "nds",
    src: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3oj6.jpg",
  },
  {
    name: "Dekisugi Tingle Pack",
    year: 2009,
    console: "nds",
    src: "https://images.launchbox-app.com/c950c8ba-a321-4087-a277-c314b0e7f15a.png",
  },
  {
    name: "Irozuki Tincle no Koi no Balloon Trip",
    year: 2009,
    console: "nds",
    src: "https://upload.wikimedia.org/wikipedia/en/thumb/5/55/Irozuki_Tingle_no_Koi_no_Balloon_Trip.jpg/220px-Irozuki_Tingle_no_Koi_no_Balloon_Trip.jpg",
  },
  {
    name: "The Legend of Zelda: Skyward Sword",
    year: 2011,
    console: "wii",
    src: "https://upload.wikimedia.org/wikipedia/en/9/99/Legend_of_Zelda_Skyward_Sword_boxart.png",
  },
  {
    name: "The Legend of Zelda: Ocarina of Time 3D",
    year: 2011,
    console: "n3ds",
    src: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61r9KnOLBtL.jpg",
  },
  {
    name: "The Legend of Zelda: Four Swords Anniversary Edition",
    year: 2011,
    console: "gamecube",
    src: "https://lutris.net/media/igdb/cover_big/co2596.jpg",
  },
  {
    name: "The Legend of Zelda: A Link Between Worlds",
    year: 2013,
    console: "n3ds",
    src: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61qQYWIBY0L.jpg",
  },
  {
    name: "The Legend of Zelda: The Wind Waker HD",
    year: 2013,
    console: "wiiu",
    src: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51fzLgM2YlL._AC_.jpg",
  },
  {
    name: "Hyrule Warriors",
    year: 2014,
    console: "wiiu",
    src: "https://static.wikia.nocookie.net/dynastywarriors/images/d/d5/HW_Limited_Edition_Cover.png",
  },
  {
    name: "The Legend of Zelda: Tri Force Heroes",
    year: 2015,
    console: "n3ds",
    src: "https://upload.wikimedia.org/wikipedia/en/d/db/The_Legend_of_Zelda_Tri_Force_Heroes_Boxart.jpg",
  },
  {
    name: "The Legend of Zelda: Majora's Mask 3D",
    year: 2015,
    console: "n3ds",
    src: "https://www.zeldadungeon.net/wp-content/uploads/2012/02/Majoras-Mask-3D.jpg",
  },
  {
    name: "The Legend of Zelda: Twilight Princess HD",
    year: 2015,
    console: "wiiu",
    src: "https://d3tvwjfge35btc.cloudfront.net/Assets/53/792/L_p0047279253.jpg",
  },
  {
    name: "Hyrule Warriors Legends",
    year: 2016,
    console: "n3ds",
    src: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91vK1-8SnqL._AC_SX522_.jpg",
  },
  {
    name: "My Nintendo Picross: The Legend of Zelda: Twilight Princess",
    year: 2016,
    console: "n3ds",
    src: "https://images.nintendolife.com/3de2a1a614c71/my-nintendo-picross-the-legend-of-zelda-twilight-princess-cover.cover_large.jpg",
  },
  {
    name: "The Legend of Zelda: Breath of the Wild",
    year: 2017,
    console: "nswitch",
    src: "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg",
  },
  {
    name: "Hyrule Warriors: Definitive Edition",
    year: 2018,
    console: "nswitch",
    src: "https://images.eshop-prices.com/games/411/480w.jpeg",
  },
  {
    name: "Cadence of Hyrule: Crypt of the NecroDancer featuring The Legend of Zelda (2019)",
    year: 2019,
    console: "nswitch",
    src: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_1.0/c_scale,w_900/ncom/en_US/games/switch/c/cadence-of-hyrule-crypt-of-the-necrodancer-featuring-the-legend-of-zelda-switch/hero",
  },
  {
    name: "The Legend of Zelda: Link's Awakening",
    year: 2019,
    console: "nswitch",
    src: "https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_656/b_white/f_auto/q_auto/ncom/software/switch/70010000020033/df825d5fc6747b66b051f5d3ba6a412fe625ea7878b6a10c93bb8312195682b1",
  },
  {
    name: "Hyrule Warriors: Age of Calamity",
    year: 2020,
    console: "nswitch",
    src: "https://upload.wikimedia.org/wikipedia/en/e/e1/Hyrule_Warriors_Age_Of_Calamity.jpg",
  },
  {
    name: "The Legend of Zelda: Skyward Sword HD",
    year: 2021,
    console: "nswitch",
    src: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/8176VSvYCDS._AC_SY679_.jpg",
  },
  {
    name: "The Legend of Zelda: Tears Of The Kingdom",
    year: 2023,
    console: "nswitch",
    src: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg/220px-The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg",
  },
];
